chức năng đăng ký
NguyenSang2003/LTFront-End pull request #5
Opened 2024-07-04 17:29 UTC by vietnguyen2k33

2024-07-05 07:16 UTC, NguyenSang2003 requested changes
Thêm mô tả cho pull req làm.
Comment mấy cái hàm bằng tiếng việt.
Kiểm tra lại cn trc đó xem có hoạt động ko khi thêm cn mới.

2024-07-07 06:00 UTC, NguyenSang2003 commented on src/components/Chat.tsx
> +        localStorage.removeItem('messages');
Bỏ dòng này đi, vì tin nhắn sẽ lưu lại và đã có nút để xóa tin nhắn đi r

2024-07-07 06:12 UTC, vietnguyen2k33 commented on src/components/Chat.tsx
> +        localStorage.removeItem('messages');
oke

2024-07-07 06:22 UTC, NguyenSang2003 approved these changes
oke rồi

2024-07-07 06:22 UTC, merged